# Generated by Django 5.2.7 on 2025-10-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_adjustmentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustmentmodel',
            name='adjustment',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='adjustmentmodel',
            name='final_amount',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=18),
        ),
    ]
