# Generated by Django 5.2.6 on 2025-10-14 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_adjustmentmodel_adjustment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdjustmentModel',
        ),
    ]
