# Generated by Django 5.2.5 on 2025-11-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20),
        ),
    ]
