# Generated by Django 5.2.5 on 2025-11-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Gastos', 'Gastos'), ('Ingresos', 'Ingresos')], default='Ingresos', max_length=20),
        ),
    ]
